import express from "express"; import path from "path"; import {fileURLToPath} from "url"; import Database from "better-sqlite3"; import {z} from "zod";
const __dirname=path.dirname(fileURLToPath(import.meta.url)); const db=new Database("kisansathi.sqlite");
db.exec(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price REAL,discountPrice REAL,stock INTEGER,unit TEXT,image TEXT); CREATE TABLE IF NOT EXISTS farms(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,crop TEXT,area REAL,unit TEXT,sowingDate TEXT,soil TEXT,irrigation TEXT); CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,orderNo TEXT,total REAL,status TEXT,paymentMethod TEXT,customer TEXT,createdAt TEXT);`);
if((db.prepare("SELECT count(*) c FROM products").get() as any).c===0){const ins=db.prepare("INSERT INTO products(name,category,price,discountPrice,stock,unit,image) VALUES(?,?,?,?,?,?,?)"); [["HD-2967 गेहूं बीज","Seeds",850,799,40,"10 kg","🌾"],["जैविक वर्मी कम्पोस्ट","Bio Products",450,399,25,"25 kg","🌱"],["कृषि हाथ कुदाल","Farming Tools",320,null,15,"1 pc","🧰"],["ड्रिप किट","Irrigation",1299,1199,8,"1 kit","💧"]].forEach(x=>ins.run(...x));}
const app=express(); app.use(express.json({limit:"2mb"}));
app.get("/api/products",(_,res)=>res.json(db.prepare("SELECT * FROM products ORDER BY id DESC").all()));
app.get("/api/farms",(_,res)=>res.json(db.prepare("SELECT * FROM farms ORDER BY id DESC").all()));
app.post("/api/farms",(req,res)=>{const s=z.object({name:z.string().min(1),crop:z.string(),area:z.coerce.number().positive(),unit:z.string(),sowingDate:z.string(),soil:z.string(),irrigation:z.string()}).parse(req.body);const r=db.prepare("INSERT INTO farms(name,crop,area,unit,sowingDate,soil,irrigation) VALUES(@name,@crop,@area,@unit,@sowingDate,@soil,@irrigation)").run(s);res.json({...s,id:Number(r.lastInsertRowid)})});
app.get("/api/weather",(_,res)=>res.json({demo:true,source:"Demo Data",updatedAt:new Date().toISOString(),current:{temperature:28,humidity:61,wind:8,rainProbability:20},forecast:[{day:"आज",temp:28,rain:20},{day:"कल",temp:27,rain:55},{day:"परसों",temp:29,rain:15}]}));
app.get("/api/mandi-prices",(_,res)=>res.json({demo:true,source:"Demo Data",message:"Live mandi feed configured नहीं है.",data:[{mandi:"Demo Mandi",crop:"गेहूं",min:2100,max:2450,modal:2300,date:"Demo"}]}));
app.post("/api/chat",(req,res)=>{if(!process.env.AI_API_KEY)return res.json({demo:true,reply:"AI service abhi configure nahi hai. Demo mode mein app chal raha hai. आप फसल, मौसम, मिट्टी और लक्षण बताएं; मैं आपको सुरक्षित अगले कदम समझाने में मदद कर सकता हूँ।"});res.status(501).json({error:"AI provider adapter not implemented"});});
app.post("/api/crop/analyze",(req,res)=>{const crop=req.body.cropType||"फसल";res.json({demo:true,crop,issue:"पत्तियों में पोषक तत्वों की कमी जैसी समस्या संभव",confidence:"Demo / अनुमान",symptoms:"पीली पड़ती पत्तियां",causes:"मिट्टी, पानी या पोषण से जुड़े कई कारण हो सकते हैं",nextSteps:"फसल की उम्र, खेत की स्थिति और पत्तियों की तस्वीर की विशेषज्ञ/विश्वसनीय स्रोत से पुष्टि करें",prevention:"संतुलित खेती प्रबंधन रखें और स्थानीय कृषि सलाह का पालन करें"});});
app.post("/api/orders",(req,res)=>{const items=req.body.items||[];let total=0;for(const i of items){const p=db.prepare("SELECT * FROM products WHERE id=?").get(i.productId) as any;if(!p||p.stock<i.quantity)return res.status(400).send("Stock unavailable");total+=(p.discountPrice||p.price)*i.quantity}const no="KS"+Date.now().toString().slice(-8);const r=db.prepare("INSERT INTO orders(orderNo,total,status,paymentMethod,customer,createdAt) VALUES(?,?,?,?,?,?)").run(no,total,"Order Placed",req.body.paymentMethod||"COD",JSON.stringify(req.body.customer||{}),new Date().toISOString());for(const i of items)db.prepare("UPDATE products SET stock=stock-? WHERE id=?").run(i.quantity,i.productId);res.json({id:r.lastInsertRowid,orderNo:no,total,status:"Order Placed"});});
app.get("/api/orders",(_,res)=>res.json(db.prepare("SELECT * FROM orders ORDER BY id DESC").all()));
app.get("/api/schemes",(_,res)=>res.json({demo:true,message:"Verified government scheme feed configure नहीं है; demo records must not be treated as official.",data:[]}));
const dist=path.join(__dirname,"../dist");app.use(express.static(dist));app.get("*",(req,res)=>{if(req.path.startsWith("/api/"))return res.status(404).end();res.sendFile(path.join(dist,"index.html"))});app.listen(process.env.PORT||3000,()=>console.log("KisanSaathi AI server running"));
