import React,{useEffect,useState} from "react"; import {createRoot} from "react-dom/client"; import {Home,Leaf,Camera,ShoppingCart,User,MessageCircle,CloudSun,IndianRupee,BookOpen,Landmark,Plus,Minus,Trash2,ArrowLeft} from "lucide-react"; import "./style.css";

type Product={id:number,name:string,category:string,price:number,discountPrice?:number,stock:number,unit:string,image:string};
type Farm={id:number,name:string,crop:string,area:number,unit:string,sowingDate:string,soil:string,irrigation:string};
const api=async(path:string,opts?:RequestInit)=>{const r=await fetch("/api"+path,{headers:{"Content-Type":"application/json"},...opts}); if(!r.ok) throw new Error(await r.text()); return r.json()};

function App(){
 const [tab,setTab]=useState("home"); const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<Record<number,number>>({}); const [farms,setFarms]=useState<Farm[]>([]); const [chat,setChat]=useState<{role:string,text:string}[]>([]); const [q,setQ]=useState(""); const [name]=useState("Kisan Bhai"); const [doctor,setDoctor]=useState<any>(null);
 useEffect(()=>{api("/products").then(setProducts);api("/farms").then(setFarms).catch(()=>{})},[]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0);
 const total=Object.entries(cart).reduce((s,[id,n])=>{const p=products.find(x=>x.id===+id);return s+(p?(p.discountPrice||p.price)*n:0)},0);
 const ask=async()=>{if(!q.trim())return; const text=q;setQ("");setChat(c=>[...c,{role:"user",text}]);try{const x=await api("/chat",{method:"POST",body:JSON.stringify({message:text})});setChat(c=>[...c,{role:"ai",text:x.reply}])}catch{setChat(c=>[...c,{role:"ai",text:"AI service abhi configure nahi hai. Demo mode mein app chal raha hai."}])}};
 return <div className="app">
  <header><div><div className="brand">🌾 KisanSaathi AI</div><small>Aapka Digital Kisan Dost</small></div><div className="avatar">👨‍🌾</div></header>
  <main>
   {tab==="home"&&<HomePage name={name} setTab={setTab}/>}
   {tab==="crops"&&<Crops farms={farms} setFarms={setFarms}/>}
   {tab==="doctor"&&<Doctor doctor={doctor} setDoctor={setDoctor}/>}
   {tab==="store"&&<Store products={products} cart={cart} setCart={setCart}/>}
   {tab==="profile"&&<Profile name={name} setTab={setTab}/>}
   {tab==="cart"&&<Cart products={products} cart={cart} setCart={setCart} total={total}/>}
   {tab==="chat"&&<Chat chat={chat} q={q} setQ={setQ} ask={ask}/>}
  </main>
  <button className="fab" onClick={()=>setTab("chat")}><MessageCircle size={25}/><span>AI Kisan</span></button>
  <nav>{[[Home,"home","Home"],[Leaf,"crops","Meri Fasal"],[Camera,"doctor","Crop Doctor"],[ShoppingCart,"store",`Store${count?` (${count})`:``}`],[User,"profile","Profile"]].map(([I,k,t]:any)=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}><I size={22}/><span>{t}</span></button>)}</nav>
 </div>
}
function HomePage({name,setTab}:any){return <><section className="hero"><h1>Namaste {name} 👋</h1><p>आज खेती में आपकी मदद के लिए तैयार हूँ।</p><div className="weather"><CloudSun/><div><b>28°C · साफ़ मौसम</b><small>🌧️ बारिश की संभावना: 20% · Demo Data</small></div></div></section><div className="grid">
 {[[Camera,"📸","Fasal Check Karein","doctor"],[MessageCircle,"🤖","AI Kisan","chat"],[CloudSun,"🌦️","Mausam","home"],[IndianRupee,"💰","Mandi Bhav","home"],[Leaf,"🌱","Meri Fasal","crops"],[ShoppingCart,"🛒","Kisan Store","store"],[Landmark,"🏛️","Sarkari Yojana","schemes"]].map(([I,e,t,k]:any)=><button className="action" onClick={()=>setTab(k)} key={t}><span>{e}</span><div><b>{t}</b><small>देखें</small></div><I size={20}/></button>)}</div><section className="card"><b>⚠️ खेती की सलाह</b><p>कल बारिश की संभावना है। सिंचाई का निर्णय लेने से पहले स्थानीय forecast चेक करें।</p></section></>}
function Doctor({doctor,setDoctor}:any){const [crop,setCrop]=useState("गेहूं"); const [file,setFile]=useState<File|null>(null); const analyze=async()=>{const r=await api("/crop/analyze",{method:"POST",body:JSON.stringify({cropType:crop})});setDoctor(r)};return <><Title title="📸 Crop Doctor"/><div className="card"><label>फसल चुनें</label><select value={crop} onChange={e=>setCrop(e.target.value)}><option>गेहूं</option><option>धान</option><option>टमाटर</option><option>आलू</option><option>कपास</option></select><label className="upload">📷 फोटो चुनें<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<p>✓ {file.name}</p>}<button className="primary" onClick={analyze}>फसल का विश्लेषण करें</button></div>{doctor&&<div className="card"><div className="warning">AI-based preliminary assessment<br/><b>Demo Data — not a real diagnosis.</b></div><h2>{doctor.crop}</h2><p><b>संभावित समस्या:</b> {doctor.issue}</p><p><b>Confidence:</b> {doctor.confidence}</p><p><b>लक्षण:</b> {doctor.symptoms}</p><p><b>संभावित कारण:</b> {doctor.causes}</p><p><b>अगला कदम:</b> {doctor.nextSteps}</p><p><b>रोकथाम:</b> {doctor.prevention}</p><button className="secondary">📖 Khet Diary में सेव करें</button></div>}</>}
function Store({products,cart,setCart}:any){return <><Title title="🛒 KisanSaathi Store"/><div className="notice">🌾 Kheti ki zaroori cheezein ek jagah</div><input className="search" placeholder="🔎 उत्पाद खोजें..."/><div className="chips"><span>🌱 Seeds</span><span>🌾 Fertilizers</span><span>🧰 Tools</span><span>💧 Irrigation</span></div><div className="products">{products.map((p:Product)=><div className="product" key={p.id}><div className="pimg">{p.image}</div><small>{p.category}</small><b>{p.name}</b><div className="price">₹{p.discountPrice||p.price} <del>{p.discountPrice?`₹${p.price}`:""}</del></div><small>{p.stock>0?"✓ उपलब्ध":"Out of stock"} · {p.unit}</small><button disabled={!p.stock} className="primary" onClick={()=>setCart((c:any)=>({...c,[p.id]:(c[p.id]||0)+1}))}>+ Cart</button></div>)}</div></>}
function Cart({products,cart,setCart,total}:any){const [placed,setPlaced]=useState(false);const checkout=async()=>{const items=Object.entries(cart).map(([productId,quantity])=>({productId:+productId,quantity}));try{await api("/orders",{method:"POST",body:JSON.stringify({items,paymentMethod:"COD",customer:{name:"Kisan Bhai",mobile:"",address:"",village:"",district:"",state:"",pin:""}})});setPlaced(true);setCart({})}catch(e:any){alert("Order place nahi hua: "+e.message)}};return <><Title title="🛒 Cart"/>{placed?<div className="card success"><h2>🎉 Order Placed</h2><p>Cash on Delivery order demo backend mein save ho gaya.</p></div>:<><div>{Object.entries(cart).map(([id,n]:any)=>{const p=products.find((x:Product)=>x.id===+id);return p?<div className="cartrow"><span>{p.image} {p.name}</span><b>×{n}</b><button onClick={()=>setCart((c:any)=>({...c,[id]:Math.max(0,c[id]-1)}))}><Minus size={16}/></button></div>:null})}</div><div className="card totals"><p>Subtotal <b>₹{total}</b></p><p>Delivery <b>₹0</b></p><h2>Total <b>₹{total}</b></h2><button className="primary" disabled={!total} onClick={checkout}>COD से Order करें</button></div></>}</>}
function Crops({farms,setFarms}:any){const [open,setOpen]=useState(false);const [f,setF]=useState({name:"मेरा खेत",crop:"गेहूं",area:1,unit:"एकड़",sowingDate:"",soil:"दोमट",irrigation:"नहर"});const save=async()=>{const x=await api("/farms",{method:"POST",body:JSON.stringify(f)});setFarms([...farms,x]);setOpen(false)};return <><Title title="🌱 Meri Fasal"/><button className="primary" onClick={()=>setOpen(!open)}>+ नया खेत जोड़ें</button>{open&&<div className="card">{Object.keys(f).map(k=><input key={k} placeholder={k} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className="primary" onClick={save}>सेव करें</button></div>}{farms.map((x:any)=><div className="card"><h2>🌾 {x.name}</h2><p>{x.crop} · {x.area} {x.unit}</p><p>मिट्टी: {x.soil} · सिंचाई: {x.irrigation}</p><span className="tag">स्वस्थ · Demo</span></div>)}</>}
function Chat({chat,q,setQ,ask}:any){return <><Title title="🤖 AI Kisan"/><div className="chat">{chat.length===0&&<div className="ai">नमस्ते! मैं KisanSaathi AI हूँ। खेती से जुड़ा सवाल पूछिए।<br/><small>Demo mode — AI API configure नहीं है तो मैं वास्तविक AI होने का दावा नहीं करूँगा।</small></div>}{chat.map((m:any)=><div className={m.role==="user"?"user":"ai"}>{m.text}</div>)}</div><div className="composer"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="जैसे: गेहूं की पत्तियां पीली हैं..."/><button onClick={ask}>➤</button></div></>}
function Profile({name,setTab}:any){return <><Title title="👤 Profile"/><div className="profile card"><div className="bigavatar">👨‍🌾</div><h2>{name}</h2><p>📍 उत्तराखंड · Hindi</p></div><div className="card"><button onClick={()=>setTab("crops")}>🌱 मेरे खेत</button><button onClick={()=>setTab("cart")}>🛒 मेरे Orders / Cart</button><button>📖 Khet Diary</button><button>🏛️ Sarkari Yojana</button></div></>}
function Title({title}:any){return <div className="title"><h1>{title}</h1><small>सरल भाषा · किसान के लिए</small></div>}
createRoot(document.getElementById("root")!).render(<App/>);